# AI Project 3: Tech Stack Recommendation System

## Objective

The objective of this project is to build a simple recommendation system that takes user skills or interests as input, compares them with different technology-related career roles, and recommends the most suitable roles based on similarity.

This project uses recommendation logic, text matching, TF-IDF, and cosine similarity to suggest the top career paths for the user.

## Dataset Description

I created this dataset on my own to showcase my project.
The dataset contains different technology-related job roles and the skills, tools, and descriptions connected to each role.

Columns used:
- role: The career path or job role
- skills: The main skills required for the role
- tools_platforms: Tools and platforms commonly used in the role
- description: A short explanation of the role

## 1- Imports and Inspecting Dataset

In [4]:
#imports
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [59]:
#loading dataset

df = pd.read_csv("raw_skills.csv")
df = df[["role", "skills", "tools_platforms", "description"]]

In [60]:
#checking the first 5 rows
df.head()

,role,skills,tools_platforms,description
0,Data Scientist,Python SQL statistics machine learning data cl...,Python pandas NumPy scikit-learn Jupyter Matpl...,"Analyzes data, builds predictive models, and e..."
1,Data Analyst,SQL Excel Python statistics dashboards data cl...,Excel Power BI Tableau SQL Python pandas Googl...,"Turns raw data into reports, dashboards, and i..."
2,Machine Learning Engineer,Python machine learning algorithms model deplo...,Python scikit-learn TensorFlow PyTorch FastAPI...,"Builds, trains, optimizes, and deploys machine..."
3,AI Engineer,Python artificial intelligence machine learnin...,Python OpenAI API LangChain TensorFlow PyTorch...,"Develops AI-powered systems, automations, and ..."
4,Deep Learning Engineer,Python neural networks deep learning computer ...,PyTorch TensorFlow Keras CUDA Hugging Face Jup...,Designs and trains neural network models for a...

In [61]:
#checking the information of the dataset
df.info()


#checking missing values
print("-"*50)
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   role             54 non-null     object
 1   skills           54 non-null     object
 2   tools_platforms  54 non-null     object
 3   description      54 non-null     object
dtypes: object(4)
memory usage: 1.8+ KB
--------------------------------------------------

role               0
skills             0
tools_platforms    0
description        0
dtype: int64

## 2- Text Preparation

To compare the user's interests with the roles, the important text columns are combined into one column. This gives the recommendation system more information to compare against.

In [62]:
# Combining the important columns that will affect the recommendations
df["combined_text"] = df["skills"] + " " + df["tools_platforms"] + " " + df["description"]
df[["role", "combined_text"]].head()

,role,combined_text
0,Data Scientist,Python SQL statistics machine learning data cl...
1,Data Analyst,SQL Excel Python statistics dashboards data cl...
2,Machine Learning Engineer,Python machine learning algorithms model deplo...
3,AI Engineer,Python artificial intelligence machine learnin...
4,Deep Learning Engineer,Python neural networks deep learning computer ...

## 3- User Input

The user enters at least three skills or interests. These inputs will be used to find the closest matching career roles.

In [51]:
#use input
skill1 = input("Enter your first skill or interest: ").lower()
skill2 = input("Enter your second skill or interest: ").lower()
skill3 = input("Enter your third skill or interest: ").lower()

# Combining skills into one sentence
user_input = skill1 + " " + skill2 + " " + skill3

print("Your skills/interests:", user_input)

Enter your first skill or interest:  python
Enter your second skill or interest:  sql
Enter your third skill or interest:  machine learning

Your skills/interests: python sql machine learning

## 4- TF-IDF Vectorization

TF-IDF converts text into numerical values so the system can compare the user's input with each role in the dataset.

In [52]:
# Turn text into numbers so the recommendation system can compare the user's skills with each role.
vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(df["combined_text"])
user_vector = vectorizer.transform([user_input])

## 5- Cosine Similarity

Cosine similarity measures how close the user's input is to each role in the dataset. A higher similarity score means a better match.

In [53]:
#Calculating the scores
similarity_scores = cosine_similarity(user_vector, tfidf_matrix)

#Adding the scores to the dataset
df["similarity_score"] = similarity_scores[0]

## 6- Sorting and Recommendation
Sorting the roles from highest similarity score to lowest and recommending the top 3 matches.

In [54]:
#sorting,recommending and showing the table with similarity score
recommendations = df.sort_values(by="similarity_score", ascending=False).head(3)
recommendations[["role", "skills", "tools_platforms", "similarity_score"]]

,role,skills,tools_platforms,similarity_score
2,Machine Learning Engineer,Python machine learning algorithms model deplo...,Python scikit-learn TensorFlow PyTorch FastAPI...,0.421588
0,Data Scientist,Python SQL statistics machine learning data cl...,Python pandas NumPy scikit-learn Jupyter Matpl...,0.334703
7,MLOps Engineer,machine learning deployment CI/CD Docker Kuber...,Docker Kubernetes MLflow GitHub Actions AWS Az...,0.309034

## 7- Displaying Results

In [55]:
#Showing results
print("Top 3 Recommended Career Paths:\n")

for index, row in recommendations.iterrows():
    print("Role:", row["role"])
    print("Skills:", row["skills"])
    print("Tools/Platforms:", row["tools_platforms"])
    print("Similarity Score:", round(row["similarity_score"], 2))
    print("-" * 50)

Top 3 Recommended Career Paths:

Role: Machine Learning Engineer
Skills: Python machine learning algorithms model deployment feature engineering APIs optimization data pipelines
Tools/Platforms: Python scikit-learn TensorFlow PyTorch FastAPI Docker MLflow Git
Similarity Score: 0.42
--------------------------------------------------
Role: Data Scientist
Skills: Python SQL statistics machine learning data cleaning feature engineering model evaluation data visualization
Tools/Platforms: Python pandas NumPy scikit-learn Jupyter Matplotlib Seaborn SQL
Similarity Score: 0.33
--------------------------------------------------
Role: MLOps Engineer
Skills: machine learning deployment CI/CD Docker Kubernetes cloud monitoring pipelines automation versioning
Tools/Platforms: Docker Kubernetes MLflow GitHub Actions AWS Azure GCP Airflow
Similarity Score: 0.31
--------------------------------------------------

## 8- Conclusion

This project successfully built a simple recommendation system using user skills and career interests. The system compares the user's input with different technology roles and recommends the top matching career paths based on similarity scores.

Through this project, I learned how recommendation systems can use text-based matching, TF-IDF, and cosine similarity to suggest relevant options. The system is simple, but it shows the core idea behind recommendation logic.

## 9- The Final System
This final section combines all previous steps into one complete runnable recommendation system.

In [58]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df = pd.read_csv("raw_skills.csv")

df["combined_text"] = df["skills"] + " " + df["tools_platforms"] + " " + df["description"]

skill1 = input("Enter your first skill or interest: ").lower()
skill2 = input("Enter your second skill or interest: ").lower()
skill3 = input("Enter your third skill or interest: ").lower()

user_input = skill1 + " " + skill2 + " " + skill3

print("Your skills/interests:", user_input)

vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(df["combined_text"])
user_vector = vectorizer.transform([user_input])

#Calculating the scores
similarity_scores = cosine_similarity(user_vector, tfidf_matrix)

#Adding the scores to the dataset
df["similarity_score"] = similarity_scores[0]

recommendations = df.sort_values(by="similarity_score", ascending=False).head(3)
recommendations[["role", "skills", "tools_platforms", "similarity_score"]]

print("Top 3 Recommended Career Paths:\n")

for index, row in recommendations.iterrows():
    print("Role:", row["role"])
    print("Skills:", row["skills"])
    print("Tools/Platforms:", row["tools_platforms"])
    print("Similarity Score:", round(row["similarity_score"], 2))
    print("-" * 50)

Enter your first skill or interest:  python
Enter your second skill or interest:  c++
Enter your third skill or interest:  programming

Your skills/interests: python c++ programming
Top 3 Recommended Career Paths:

Role: Python Developer
Skills: Python programming scripting automation APIs databases debugging data processing
Tools/Platforms: Python Flask Django FastAPI pandas pytest Git VS Code
Similarity Score: 0.3
--------------------------------------------------
Role: Software Engineer
Skills: programming algorithms data structures debugging testing software design problem solving Git
Tools/Platforms: Python Java C++ Git GitHub VS Code IntelliJ Linux
Similarity Score: 0.19
--------------------------------------------------
Role: IoT Engineer
Skills: sensors networking embedded systems cloud data collection automation electronics programming
Tools/Platforms: Arduino Raspberry Pi MQTT AWS IoT Python C++ Node-RED
Similarity Score: 0.16
--------------------------------------------------